spring:
  datasource:
    url: jdbc:mysql://localhost:13306/pilot?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: woowa
    password: woowa

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      open-in-view: false